export const signInFormLabelsInfo = [
    {
        labelClassName: "form__label_type_login",
        spanHint: "Логин",
        inputId: "input__login",
        inputName: "login",
        inputType: "text",
        inputPlaceHolder: "vitklassen",
        ariaDescribedby: "login-error",
        validPattern: "[a-zA-Z]{2,30}$", //добавить нормальное регулярное выражение
        errorMessage: "Неверный логин",
        errorClassname: "input__login-error",
        minLength: 3,
        maxLength: 20,
        required: true
    },
    {
        labelClassName: "form__label_type_login",
        spanHint: "Пароль",
        inputId: "input__password",
        inputName: "password",
        inputType: "password",
        inputPlaceHolder: "Пароль",
        ariaDescribedby: "password-error",
        validPattern: "[a-zA-Z]{8,40}$", //добавить нормальное регулярное выражение
        errorMessage: "Неверный пароль",
        errorClassname: "input__password-error",
        minLength: 8,
        maxLength: 40,
        required: true
    }
];

export const signUpFormLabelsInfo = [
    {
        labelClassName: "form__label_type_register",
        spanHint: "Почта",
        inputId: "input__email",
        inputName: "email",
        inputType: "email",
        inputPlaceHolder: "Виктор",
        ariaDescribedby: "email-error",
        validPattern: "[a-zA-Z]{2,30}$", //добавить нормальное регулярное выражение
        errorMessage: "Неверный формат почты",
        errorClassname: "input__email-error",
        minLength: 0,
        maxLength: 100000,
    },
    {
        labelClassName: "form__label_type_register",
        spanHint: "Логин",
        inputId: "input__login",
        inputName: "login",
        inputType: "text",
        inputPlaceHolder: "vitklassen",
        ariaDescribedby: "login-error",
        validPattern: "[a-zA-Z]{2,30}$", //добавить нормальное регулярное выражение
        errorMessage: "Неверный логин",
        errorClassname: "input__login-error",
        minLength: 3,
        maxLength: 20,
    },
    {
        labelClassName: "form__label_type_register",
        spanHint: "Имя",
        inputId: "input__first_name",
        inputName: "first_name",
        inputType: "text",
        inputPlaceHolder: "Виктор",
        ariaDescribedby: "first_name-error",
        validPattern: "[a-zA-Z]{2,30}$", //добавить нормальное регулярное выражение
        errorMessage: "Неверный формат имени",
        errorClassname: "input__first_name-error",
        minLength: 0,
        maxLength: 100000,
    },
    {
        labelClassName: "form__label_type_register",
        spanHint: "Фамилия",
        inputId: "input__second_name",
        inputName: "second_name",
        inputType: "text",
        inputPlaceHolder: "Классен",
        ariaDescribedby: "second_name-error",
        validPattern: "[a-zA-Z]{2,30}$", //добавить нормальное регулярное выражение
        errorMessage: "Неверный формат фамилии",
        errorClassname: "input__second_name-error",
        minLength: 0,
        maxLength: 100000,
    },
    {
        labelClassName: "form__label_type_register",
        spanHint: "Телефон",
        inputId: "input__phone",
        inputName: "phone",
        inputType: "tel",
        inputPlaceHolder: "+7-(800)-555-35-35",
        ariaDescribedby: "phone-error",
        validPattern: "[0-9]{2,30}$", //добавить нормальное регулярное выражение
        errorMessage: "Неверный формат телефона",
        errorClassname: "input__phone-error",
        minLength: 0,
        maxLength: 100000,
    },
    {
        labelClassName: "form__label_type_login",
        spanHint: "Пароль",
        inputId: "input__password_1",
        inputName: "password",
        inputType: "password",
        inputPlaceHolder: "Пароль",
        ariaDescribedby: "password_1-error",
        validPattern: "[a-zA-Z]{8,40}$", //добавить нормальное регулярное выражение
        errorMessage: "Неверный пароль",
        errorClassname: "input__password_1-error",
        minLength: 8,
        maxLength: 40,
    },
    {
        labelClassName: "form__label_type_login",
        spanHint: "Пароль (еще раз)",
        inputId: "input__password_2",
        inputName: "password",
        inputType: "password",
        inputPlaceHolder: "Пароль",
        ariaDescribedby: "password_2-error",
        validPattern: "[a-zA-Z]{8,40}$", //добавить нормальное регулярное выражение
        errorMessage: "Неверный пароль",
        errorClassname: "input__password_2-error",
        minLength: 8,
        maxLength: 40,
    },
];

export const profileChangeData = [
    {
        inputId: 'input__email',
        labelText: 'Почта',
        inputName: 'email',
        inputType: 'email',
        inputPlaceHolder:'vit.klassen@yandex.ru',
        ariaDescribedby: 'email-error',
        validPattern: '',
        errorMessage: '',
        minLength: 0,
        maxLength: 10000,
        disabled: true,
        required: true,
    },
    {
        inputId: 'input__login',
        labelText: 'Логин',
        inputName: 'login',
        inputType: 'text',
        inputPlaceHolder:'vitklassen',
        ariaDescribedby: 'login-error',
        validPattern: '',
        errorMessage: '',
        minLength: 0,
        maxLength: 10000,
        disabled: true,
        required: true,
    },
    {
        inputId: 'input__first_name',
        labelText: 'Имя',
        inputName: 'first_name',
        inputType: 'text',
        inputPlaceHolder:'Виктор',
        ariaDescribedby: 'first_name-error',
        validPattern: '',
        errorMessage: '',
        minLength: 0,
        maxLength: 10000,
        disabled: true,
        required: true,
    },
    {
        inputId: 'input__second_name',
        labelText: 'Фамилия',
        inputName: 'second_name',
        inputType: 'text',
        inputPlaceHolder:'Классен',
        ariaDescribedby: 'second_name-error',
        validPattern: '',
        errorMessage: '',
        minLength: 0,
        maxLength: 10000,
        disabled: true,
        required: true,
    },
    {
        inputId: 'input__display_name',
        labelText: 'Имя в чате',
        inputName: 'display_name',
        inputType: 'text',
        inputPlaceHolder:'Витто',
        ariaDescribedby: 'display_name-error',
        validPattern: '',
        errorMessage: '',
        minLength: 0,
        maxLength: 10000,
        disabled: true,
        required: true,
    },
    {
        inputId: 'input__phone',
        labelText: 'Телефон',
        inputName: 'phone',
        inputType: 'tel',
        inputPlaceHolder:'8 800 555 35 35',
        ariaDescribedby: 'phone-error',
        validPattern: '',
        errorMessage: '',
        minLength: 0,
        maxLength: 10000,
        disabled: true,
        required: true,
    }
];

export const passwordChangeData = [
    {
        inputId: 'input__oldPassword',
        labelText: 'Старый пароль',
        inputName: 'oldPassword',
        inputType: 'password',
        ariaDescribedby: 'oldPassword-error',
        validPattern: '',
        errorMessage: '',
        minLength: 0,
        maxLength: 10000,
        disabled: false,
        required: true,
    },
    {
        inputId: 'input__newPassword_1',
        labelText: 'Новый пароль',
        inputName: 'newPassword',
        inputType: 'password',
        ariaDescribedby: 'newPassword_1-error',
        validPattern: '',
        errorMessage: '',
        minLength: 0,
        maxLength: 10000,
        disabled: false,
        required: true,
    },
    {
        inputId: 'input__newPassword_2',
        labelText: 'Повторите новый пароль',
        inputName: 'newPassword',
        inputType: 'password',
        ariaDescribedby: 'newPassword_2-error',
        validPattern: '',
        errorMessage: '',
        minLength: 0,
        maxLength: 10000,
        disabled: false,
        required: true,
    }
]